version: '3.6'

networks:
  network-shared:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: panayi
    networks:
      - 'network-shared'
    volumes:
      - '/var/lib/postgresql/data'
  test:
    image: mon_image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      IP: 0.0.0.0
      PORT: 8000
      POSTGRES_URL: 'db'
      POSTGRES_PASSWORD: panayi
    ports:
      - 8000:8000
    depends_on:
      - 'db'
    links:
      - 'db'
    networks:
      - 'network-shared'
